import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import ThemeToggle from "@/components/common/ThemeToggle";

export const metadata: Metadata = {
  title: "Lynx Media",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <ThemeProvider>
          <TRPCReactProvider>
            {children}
            <ThemeToggle />
          </TRPCReactProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
