// src/lib/catalog/mockTracks.ts
import type { Track } from "./types";

export const MOCK_TRACKS: Track[] = [
  {
    id: "lm-001",
    title: "Midnight Chase",
    artist: "Dtrip / Lynx Music",
    moods: ["Tenso", "Cinemático", "Oscuro"],
    uses: ["Trailer", "Serie", "Acción"],
    bpm: 132,
    duration: "2:14",
    key: "Fm",
    audioUrl: "https://pub-1ebab5693cb54e69a0bd8c0ea2f5390f.r2.dev/audio/2025/11/19/20ccca9c-6052-4b6e-b173-5d1f32d875ee-d-svdd-epic-dark-shorts-1.mp3",
  },
  {
    id: "lm-002",
    title: "Concrete Jungle",
    artist: "Dtrip / Lynx Music",
    moods: ["Urbano", "Crudo", "Profundo"],
    uses: ["Serie", "Drama", "Publicidad"],
    bpm: 88,
    duration: "2:48",
    key: "Cm",
    audioUrl: "/audio/demo/concrete-jungle.mp3",
  },
  {
    id: "lm-003",
    title: "Neon Skyline",
    artist: "Lynx Music Collective",
    moods: ["Retro", "Synthwave", "Melancólico"],
    uses: ["Film", "Sci-Fi", "Main Titles"],
    bpm: 118,
    duration: "3:05",
    key: "Em",
    audioUrl: "/audio/demo/neon-skyline.mp3",
  },
  {
    id: "lm-004",
    title: "Silent Waters",
    artist: "Lynx Music Collective",
    moods: ["Íntimo", "Emotivo", "Orgánico"],
    uses: ["Documental", "Drama", "Human Stories"],
    bpm: 72,
    duration: "2:37",
    key: "Am",
    audioUrl: "/audio/demo/silent-waters.mp3",
  },
  {
    id: "lm-005",
    title: "Signal Lost",
    artist: "Dtrip / Lynx Music",
    moods: ["Tenso", "Tecnológico", "Abstracto"],
    uses: ["Trailer", "Thriller", "Tech"],
    bpm: 140,
    duration: "2:01",
    key: "Gm",
    audioUrl: "/audio/demo/signal-lost.mp3",
  },
  {
    id: "lm-006",
    title: "Golden Hour Streets",
    artist: "Lynx Music Collective",
    moods: ["Warm", "Esperanzador", "Urbano"],
    uses: ["Publicidad", "Lifestyle", "Redes"],
    bpm: 100,
    duration: "2:26",
    key: "Bb",
    audioUrl: "/audio/demo/golden-hour-streets.mp3",
  },
];
